### ISSUE TITLE
🔄 Add Reresh Random Image Button

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pixel-banner#43]
Hi, I see the new Pin feature and think it's great, and I think -
We can now have multiple images randomized, and sometimes the random ones that I don't like very much, can we use a command to "refresh" them?
Also, is it possible to "blacklist" a specific image and no longer show it?

The second requirement may require storing more data, which is a bit cumbersome...... I think it's enough to have a manual refresh function at the moment!

**Comment by jparkerweb** [comment]
@Moyf 
![Image](https://github.com/user-attachments/assets/fe4acac2-bb77-4073-8bf6-afa7afdba7ff)

**Comment by Moyf** [comment]
It's so fast, thanks for the development!!

---

By the way, I did some css customization for the Pin icon (it's not FR, just to share 😸):

```css

.pin-icon {
    /* display: none !important; */
    padding-left: 1em;
    padding-top: 0.5em;
    opacity: 0.2;
    font-size: 1em !important;
}

.pin-icon:hover {
    /* display: none !important; */
    opacity: 1.0;
}
```

In this way, it itself will not take up too much attention, and it will be good to move over when needed~
![01d557ef-c133-4004-9bfb-ed0f96c1d34c](https://github.com/user-attachments/assets/ed6e1bb7-6052-4241-92c9-d562af72c24f)
