### ISSUE TITLE
❓ Local image dont display in reading view in mobile

### ISSUE THREAD

**Issue by samaellain** [jparkerweb/pixel-banner#71]
In mobile, local image like [[image.jpg]] only display in live preview and not in reading view.
URL display in both modes in mobile.
Desktop version, both modes display correct.

![Screenshot_2024-11-30-03-09-27-667_md obsidian](https://github.com/user-attachments/assets/33e885d5-f00d-45ea-88ee-b93c61bbda9e)
![Screenshot_2024-11-30-03-09-32-333_md obsidian](https://github.com/user-attachments/assets/ad68e9b1-8c11-4b02-b573-d0fcfd66da41)

**Comment by jparkerweb** [comment]
thank you, I will take a look

**Comment by jparkerweb** [comment]
![Screenshot_20241130-081057.png](https://github.com/user-attachments/assets/03c70adb-6ebd-4897-ae86-1b7976185de7)

I can't seem to reproduce your issue.
Can you make sure you're on the latest version of the plugin.  If you still have the issue can you create a sample vault that recreates the issue and share it please.

Feel free  to join the community and discuss the issue on our Discord as well:
https://discord.gg/sp8AQQhMJ7

**Comment by samaellain** [comment]
I am only in mobile now and in a new vault the problem dont happen. Sorry for inconvenience.
Closing the issue.
Found the problem. The custom css i use for chance the background.
```css
.homepage.markdown-preview-view{
    
    background-color: rgb(249, 250, 251);
}
.homepage.markdown-source-view{
    
    background-color: rgb(249, 250, 251);
}
``` 
The image is in a zindex behind probably.
